- name: RabbitMQ Setup
  hosts: all
  become: true
  tasks:
    - name: Install Erlang Repos
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

    - name: Install RabbitMQ Repos
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: Install RabbitMQ Server
      ansible.builtin.yum:
        name: rabbitmq-sever
        state: restarted

    - name: Install RabbitMQ Service
      ansible.builtin.yum:
        name: rabbitmq-sever
        state: restarted
        enabled: yes

    - name: Start Applications User
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present




